development:
  bucket: wb-shipping-manifest-development
  access_key_id: AKIAJCCHONQAJQSYJCPQ
  secret_access_key: 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

test:
  bucket: wb-shipping-manifest-test
  access_key_id: AKIAJCCHONQAJQSYJCPQ
  secret_access_key: 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

production:
  bucket: wb-shipping-manifest
  access_key_id: AKIAJCCHONQAJQSYJCPQ
  secret_access_key: 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
