development:
  bucket: wb-shipping.dev
  access_key_id: AKIAIITWZB2PBUGGNJNQ
  secret_access_key: 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

test:
  bucket: wb-shipping.test
  access_key_id: AKIAIITWZB2PBUGGNJNQ
  secret_access_key: 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

production:
  bucket: wb-shipping
  access_key_id: AKIAIITWZB2PBUGGNJNQ
  secret_access_key: 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
