development:
  bucket: appname.dev
  access_key_id: XXXXXXXXXXXXX
  secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXX

test:
  bucket: appname.test
  access_key_id: XXXXXXXXXXXXX
  secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXX

production:
  bucket: appname.com
  access_key_id: XXXXXXXXXXXXX #change these once they get their own s3 account
  secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
